database:
    master:
        engine: "postgres"
        username: "tachyon"
        password: "Bvd^412"
        host:     "staging2"
        port:     "5432"
        db:       "test"
    slaves:
        - database.slave1
    slave1:
        engine: "postgres"
        username: "tachyon"
        password: "Bvd^412"
        host:     "staging2"
        port:     "5432"
        db:       "test"